language: node_js
node_js: node
cache:
  directories:
    "node_modules"
script:
  - yarn lint
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: churrastri
  on:
    branch: master
    all_branches: false
    repo: joaaomanooel/churras-tri-api
