version: '3.4'

services:
  # Redis
  redis:
    container_name: redis-server
    restart: on-failure
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - churrastri-api

  # API
  churrastri:
    container_name: churrastri-api
    restart: on-failure
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    links:
      - redis
    networks:
      - churrastri-api
    volumes:
      - .:/usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    command: sh -c 'wait-for redis:6379 -- yarn dev'

networks:
  churrastri-api:
    driver: "bridge"
